services:
  api:
    image: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - POSTGRES_CONNECTION="Server=database;Port=5432;Database=${POSTGRES_DB:-repoapi};Username=${POSTGRES_USER:-user};Password=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD env variable is required};Include Error Detail=true"
    depends_on:
      - database
      - cache
    networks:
      - skyblockrepo-network
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    command: -c 'max_connections=${POSTGRES_MAX_CONNECTIONS:-100}'
    ports:
      - '${POSTGRES_PORT:?POSTGRES_PORT env variable is required}:5432'
    expose:
      - '${POSTGRES_PORT:?POSTGRES_PORT env variable is required}'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - skyblockrepo-network
  cache:
    image: redis:7.4.1
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD env variable is required}
    ports:
      - '${REDIS_PORT:?REDIS_PORT env variable is required}:6379'
    expose:
      - '${REDIS_PORT:?REDIS_PORT env variable is required}'
    volumes:
      - redis-data:/data
    networks:
      - skyblockrepo-network